/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, css, customElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSContentBlock from '../content-block/content-block';
import styles from './content-block-segmented.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Simple version of content block.
 *
 * @element dds-content-block-segmented
 * @slot media - The media content.
 */
@customElement(`${ddsPrefix}-content-block-segmented`)
class DDSContentBlockSegmented extends StableSelectorMixin(DDSContentBlock) {
  protected _renderInnerBody() {
    const { _hasContent: hasContent, _hasMedia: hasMedia, _handleSlotChange: handleSlotChange } = this;
    return html`
      <div ?hidden="${!hasContent && !hasMedia}" class="${prefix}--content-block__children">
        <div class="${prefix}--content-block-segmented__media">
          <div ?hidden="${!hasMedia}">
            <slot name="media" @slotchange="${handleSlotChange}"></slot>
          </div>
          <div ?hidden="${!hasContent}">
            <slot @slotchange="${handleSlotChange}"></slot>
          </div>
        </div>
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-block-segmented`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSContentBlockSegmented;
