/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, html } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './promo-group.scss';
import DDSContentSection from '../content-section/content-section';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The Promo Group pattern
 *
 * @element dds-promo-group
 */
@customElement(`${ddsPrefix}-promo-group`)
class DDSPromoGroup extends StableSelectorMixin(DDSContentSection) {
  /**
   * Applies section attribute
   */
  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'section');
    }
    super.connectedCallback();
  }

  render() {
    return html`
      <div class="${prefix}--content-section__grid">
        <div class="${prefix}--content-section__row">
          <div class="${prefix}--content-section__left">
            <slot name="heading"></slot>
          </div>
          <div class="${prefix}--content-section__children">
            <div class="${prefix}--promo-group__heading">
              <slot name="group-heading"></slot>
            </div>
            <div class="${prefix}--promo-group__items">
              <slot name="group-items"></slot>
            </div>
          </div>
        </div>
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--promo-group`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSPromoGroup;
