/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import BXBreadcrumbLink from '@carbon/carbon-web-components/es/components/breadcrumb/breadcrumb-link.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './leadspace.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Breadcrumb link.
 *
 * @element dds-breadcrumb-link
 */
@customElement(`${ddsPrefix}-breadcrumb-link`)
class DDSBreadcrumbLink extends StableSelectorMixin(BXBreadcrumbLink) {
  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static styles = styles;
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSBreadcrumbLink;
