/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css, customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import DDSImage from '../image/image';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './leadspace.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;
/**
 * Custom leadspace image.
 *
 * @element dds-leadspace-image
 */
@customElement(`${ddsPrefix}-leadspace-image`)
class DDSLeadspaceImage extends StableSelectorMixin(DDSImage) {
  static get stableSelector() {
    return `${ddsPrefix}--image`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSLeadspaceImage;
