/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element';
import settings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import styles from './button-group.scss';
import C4DButton from '../button/button';

const { stablePrefix: c4dPrefix } = settings;

/**
 * Button group item.
 *
 * @element c4d-button-group-item
 */
@customElement(`${c4dPrefix}-button-group-item`)
class C4DButtonGroupItem extends C4DButton {
  static get stableSelector() {
    return `${c4dPrefix}--button-group-item`;
  }

  connectedCallback() {
    super.connectedCallback();
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'listitem');
    }
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default C4DButtonGroupItem;
