/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import ArrowRight20 from 'carbon-web-components/es/icons/arrow--right/20.js';
import settings from 'carbon-components/es/globals/js/settings';
import { baseFontSize, breakpoints } from '@carbon/layout';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './universal-banner.scss';
import StickyHeader from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/StickyHeader/StickyHeader';

const gridLgBreakpoint = parseFloat(breakpoints.lg.width) * baseFontSize;

const { stablePrefix: ddsPrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Universal banner
 *
 * @element dds-universal-banner
 */
@customElement(`${ddsPrefix}-universal-banner`)
class DDSUniversalBanner extends StableSelectorMixin(LitElement) {
  /**
   * Saves the button CTA's copy to use in link-with-icon for the small breakpoint
   */
  @property()
  buttonCopy;

  /**
   * Saves the button CTA's href to use in link-with-icon for the small breakpoint
   */
  @property()
  buttonHref;

  /**
   * `true` if there is an image.
   */
  @property({ attribute: 'has-image', reflect: true, type: Boolean })
  hasImage = false;

  /**
   * Grid media options to display image.
   * Available options are either '4-col' or '8-col'.
   */
  @property({ attribute: 'image-width', reflect: true, type: String })
  imageWidth;

  private _breakpoint?: MediaQueryList;

  private _shouldRenderAsLink = false;

  /**
   * Handles `slotchange` event on the cta `<slot>`.
   */
  protected _handleImageSlotChange({ target }: Event) {
    this.hasImage = (target as HTMLSlotElement)
      .assignedNodes()
      .some(node => node.nodeType !== Node.TEXT_NODE || node!.textContent!.trim());

    if (this.hasImage && !this.imageWidth) {
      this.imageWidth = '4-col';
    }
  }

  /**
   * Handles `slotchange` event on the cta `<slot>`.
   */
  protected _handleButtonSlotChange({ target }: Event) {
    const hasContent = (target as HTMLSlotElement)
      .assignedNodes()
      .filter(elem => (elem as HTMLElement).matches?.((this.constructor as typeof DDSUniversalBanner).ctaButton));

    this.buttonHref = (hasContent[0] as HTMLElement)?.getAttribute('href');
    this.buttonCopy = hasContent[0]?.textContent?.trim();
  }

  protected _handleResize() {
    const { _breakpoint: breakpoint } = this;

    this._shouldRenderAsLink = !breakpoint!.matches;
    this.requestUpdate();
  }

  firstUpdated() {
    StickyHeader.global.banner = this;

    this._breakpoint = window.matchMedia(`(min-width: ${gridLgBreakpoint}px)`);
    this._breakpoint.addEventListener('change', this._handleResize.bind(this));
    this._handleResize();
  }

  updated() {
    this.querySelector((this.constructor as typeof DDSUniversalBanner).ctaButton)?.removeAttribute('role');
  }

  /**
   * Renders shadow dom within a static div
   */
  _renderAsStatic() {
    return html`
      <div class="${prefix}--universal-banner-layout-container">
        ${this._renderInnerContents()}
      </div>
    `;
  }

  _renderAsLink() {
    return html`
      <a href="${this.buttonHref}" class="${prefix}--universal-banner-layout-container">
        ${this._renderInnerContents()}
      </a>
    `;
  }

  _renderInnerContents() {
    return html`
      <div class="${prefix}--universal-banner-content-wrapper">
        <div ?hidden="${!this.hasImage}" class="${prefix}--universal-banner-image-container">
          <slot name="image" @slotchange="${this._handleImageSlotChange}"></slot>
        </div>

        <div class="${prefix}--universal-banner-text-container">
          <slot name="heading"></slot>
          <slot name="copy"></slot>
        </div>

        <div class="${prefix}--universal-banner-cta-container">
          <slot name="cta" @slotchange="${this._handleButtonSlotChange}"></slot>
        </div>

        <div class="${prefix}--universal-banner-icon">
          ${ArrowRight20()}
        </div>
      </div>
    `;
  }

  render() {
    return html`
      ${this._shouldRenderAsLink ? this._renderAsLink() : this._renderAsStatic()}
    `;
  }

  /**
   * A selector that will return the CTA button
   */
  static get ctaButton() {
    return `${ddsPrefix}-button-cta`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSUniversalBanner;
