/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property, query } from 'lit/decorators.js';
import settings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './button.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element.js';
import CTAMixin from '../../component-mixins/cta/cta';
import CDSButton from '../../internal/vendor/@carbon/web-components/components/button/button.js';

import { ariaLabels, icons } from '../../component-mixins/cta/cta';
const { prefix, stablePrefix: c4dPrefix } = settings;

/**
 * Button.
 *
 * @element c4d-button
 * @csspart button - The button. Usage: `c4d-button::part(button)`.
 */
@customElement(`${c4dPrefix}-button`)
// @ts-ignore
class C4DButton extends CTAMixin(StableSelectorMixin(CDSButton)) {
  @query('a')
  _linkNode;

  @property()
  iconDiv;

  @property()
  span;

  /**
   * `true` if expressive theme enabled.
   */
  @property({ type: Boolean, reflect: true })
  isExpressive = true;

  _handleDisabledClick(event: Event) {
    super._handleClick(event as any);
  }

  /**
   * TODO: Due to the new render() logic coming from the CWC v2 button,
   * this function is currently unused. We'd need to dynamically add it.
   *
   * @returns The icon for the print styles
   */
  _renderIconPrintStyles() {
    return html`
      <p class="${prefix}--btn--hidden" aria-hidden="true">
        <span>:</span> ${this.href}
      </p>
      <slot name="icon"></slot>
    `;
  }

  /**
   * @returns The template for the icon.
   */
  _renderButtonIcon() {
    const { ctaType } = this;
    const icon = icons[`${ctaType}-${document.dir}`] ?? icons[ctaType];
    return `
        <span class="${prefix}--visually-hidden">${ariaLabels[ctaType]}</span>
        ${icon?.()?.strings?.join()}
      `;
  }

  /**
   * Handles button video title
   *
   * @param event The event.
   */
  // @ts-ignore: The decorator refers to this method but TS thinks this method is not referred to
  private _handleVideoTitleUpdate = async (event) => {
    if (event) {
      const { videoDuration, videoName } = event.detail as any;
      const { formatVideoDuration, formatVideoCaption } = this;
      const formattedVideoDuration = formatVideoDuration({
        duration: !videoDuration ? videoDuration : videoDuration * 1000,
      });
      this.videoDuration ? null : (this.videoDuration = formattedVideoDuration);

      this.videoTitle = formatVideoCaption({
        duration: formattedVideoDuration,
        name: videoName,
      });

      if (this.textContent?.trim() === '') {
        const title = document.createTextNode(this.videoTitle);
        this.appendChild(title);
      }
    }
  };

  connectedCallback() {
    super.connectedCallback();
    const { eventRequestAdditionalVideoData } = this
      .constructor as typeof C4DButton;
    document.addEventListener(
      eventRequestAdditionalVideoData,
      this._handleVideoTitleUpdate
    );
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    const { eventRequestAdditionalVideoData } = this
      .constructor as typeof C4DButton;
    document.removeEventListener(
      eventRequestAdditionalVideoData,
      this._handleVideoTitleUpdate
    );
  }

  updated(changedProperties) {
    super.updated(changedProperties);

    if (changedProperties.has('ctaType')) {
      if (!this.iconDiv) {
        this.iconDiv = this.shadowRoot?.querySelector("slot[name='icon']");
      }

      const { iconDiv } = this;

      iconDiv.querySelector('svg')?.remove();
      iconDiv.innerHTML = this._renderButtonIcon();
      iconDiv
        ?.querySelector('svg')
        ?.classList.add(`${prefix}--card__cta`, `${c4dPrefix}-ce--cta__icon`);
    }
  }

  static get stableSelector() {
    return `${c4dPrefix}--button`;
  }

  /**
   * The name of the custom event fired when there is a user gesture to run the action.
   */
  static get eventRequestAdditionalVideoData() {
    return `${c4dPrefix}-cta-request-additional-video-data`;
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default C4DButton;
