/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css, customElement, html } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import DDSContentBlock from '../content-block/content-block';
import '../content-item/content-item';
import '../horizontal-rule/horizontal-rule';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './content-group-horizontal.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Horizontal version of content group.
 *
 * @element dds-content-group-horizontal
 */
@customElement(`${ddsPrefix}-content-group-horizontal`)
class DDSContentGroupHorizontal extends StableSelectorMixin(DDSContentBlock) {
  render() {
    return html`
      <slot name="heading"></slot>
      ${this._renderBody()}
      <dds-hr></dds-hr>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-group-horizontal`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSContentGroupHorizontal;
