/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css, html } from 'lit';
import settings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import C4DContentItem from '../content-item/content-item';
import styles from './content-block-headlines.scss';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';

const { stablePrefix: c4dPrefix } = settings;

/**
 * Content Block Headlines item
 *
 * @element c4d-content-block-headlines-item
 */
@customElement(`${c4dPrefix}-content-block-headlines-item`)
class C4DContentBlockHeadlinesItem extends StableSelectorMixin(C4DContentItem) {
  render() {
    return html`
      <h4 class="cds--content-block-headlines__heading">
        <slot name="heading"></slot>
      </h4>
      <p class="cds--content-block-headlines__copy">
        <slot name="copy"></slot>
      </p>
      <slot name="footer"></slot>
    `;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }

  static get stableSelector() {
    return `${c4dPrefix}--content-block-headlines-item`;
  }
}

export default C4DContentBlockHeadlinesItem;
