/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement } from 'lit-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSContentItemHeading from '../content-item/content-item-heading';
import styles from './content-block-headlines.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The heading content in content item.
 *
 * @element dds-content-block-headlines-heading
 */
@customElement(`${ddsPrefix}-content-block-headlines-heading`)
class DDSContentBlockHeadlinesHeading extends StableSelectorMixin(DDSContentItemHeading) {
  /**
   * The shadow slot this logo UI should be in.
   */
  @property({ reflect: true })
  slot = 'heading';

  render() {
    return html`
      <slot></slot>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-block-headlines__heading`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSContentBlockHeadlinesHeading;
