/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import BXSearch from 'carbon-web-components/es/components/search/search.js';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import styles from './search.scss';

export { SEARCH_COLOR_SCHEME } from 'carbon-web-components/es/components/search/search.js';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Expressive search.
 *
 * @element dds-search
 */
@customElement(`${ddsPrefix}-search`)
class DDSSearch extends BXSearch {
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSSearch;
