/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit-html/directives/class-map';
import { html, property, internalProperty, LitElement, TemplateResult } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import ifNonNull from 'carbon-web-components/es/globals/directives/if-non-null.js';
import '../markdown/markdown';
import styles from './content-block.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The table mapping slot name with the private property name that indicates the existence of the slot content.
 */
const slotExistencePropertyNames = {
  complementary: '_hasComplementary',
  cta: '_hasCTA',
};

/**
 * The style scheme for the complementary content.
 */
export enum CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME {
  /**
   * Regular style.
   */
  REGULAR = 'regular',

  /**
   * A style with border.
   */
  WITH_BORDER = 'with-border',
}

// TODO: Figure out how to define a mixin type supporting abstract class
/**
 * Content block.
 *
 * @abstract
 */
class DDSContentBlock extends LitElement {
  /**
   * `true` if there is complementary content.
   */
  @internalProperty()
  protected _hasComplementary = false;

  /**
   * `true` if there is CTA content.
   */
  @internalProperty()
  protected _hasCTA = false;

  /**
   * Handles `slotchange` event.
   *
   * @param event The event.
   */
  protected _handleSlotChange({ target }: Event) {
    const { name } = target as HTMLSlotElement;
    const hasContent = (target as HTMLSlotElement)
      .assignedNodes()
      .some(node => node.nodeType !== Node.TEXT_NODE || node!.textContent!.trim());
    this[slotExistencePropertyNames[name] || '_hasContent'] = hasContent;
  }

  /**
   * @returns The content, that may be wrapped in a Carbon grid.
   */
  protected _renderBody(): TemplateResult | string | void {
    const { _hasCTA: hasCTA } = this;
    return html`
      ${this._renderCopy()}${this._renderContent()}
      <div ?hidden="${!hasCTA}" class="${prefix}--content-block__cta-row">
        <div class="${prefix}--content-block__cta ${prefix}--content-block__cta-col">
          <slot name="cta" @slotchange="${this._handleSlotChange}"></slot>
        </div>
      </div>
    `;
  }

  /**
   * @returns The main content.
   */
  // eslint-disable-next-line class-methods-use-this
  protected _renderContent(): TemplateResult | string | void {
    return html`
      <div class="${prefix}--content-block__children">
        <slot></slot>
      </div>
    `;
  }

  /**
   * @returns The copy content.
   */
  protected _renderCopy(): TemplateResult | string | void {
    const { copy } = this;
    return html`
      ${!copy
        ? undefined
        : html`
            <dds-markdown class="${prefix}--content-block__copy" nobold .content="${ifNonNull(copy)}"></dds-markdown>
          `}
    `;
  }

  /**
   * The style scheme for the complementary content.
   */
  @property({ attribute: 'complementary-style-scheme' })
  complementaryStyleScheme = CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME.REGULAR;

  /**
   * The copy content.
   */
  @property()
  copy = '';

  render() {
    const { complementaryStyleScheme, _hasComplementary: hasComplementary } = this;
    const complementaryRowClasses = classMap({
      [`${prefix}--row`]: true,
      [`${prefix}--layout--border`]: complementaryStyleScheme === CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME.WITH_BORDER,
    });

    return !hasComplementary
      ? html`
          <slot name="heading"></slot>
          ${this._renderBody()}
          <slot name="complementary" @slotchange="${this._handleSlotChange}"></slot>
        `
      : html`
          <div class="${prefix}--row">
            <div class="${ddsPrefix}-ce--content-block__col">
              <slot name="heading"></slot>
              <div></div>
            </div>
          </div>
          <div class="${complementaryRowClasses}">
            <div class="${ddsPrefix}-ce--content-block__col">
              ${this._renderBody()}
              <slot name="complementary" @slotchange="${this._handleSlotChange}"></slot>
            </div>
          </div>
        `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSContentBlock;
