/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement, internalProperty } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import { stripHTML } from '@carbon/ibmdotcom-utilities/es/utilities/stripHTML/index.js';
import { render } from 'lit-html';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './content-block.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The heading content in content block.
 *
 * @element dds-content-block-heading
 */
@customElement(`${ddsPrefix}-content-block-heading`)
class DDSContentBlockHeading extends StableSelectorMixin(LitElement) {
  /**
   * The shadow slot this logo UI should be in.
   */
  @property({ reflect: true })
  slot = 'heading';

  @internalProperty()
  content = '';

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'heading');
    }
    if (!this.hasAttribute('aria-level')) {
      this.setAttribute('aria-level', '2');
    }
    super.connectedCallback();
  }

  firstUpdated() {
    this.content = stripHTML(this.innerHTML);
    render(
      html`
        ${this.content}
      `,
      this
    );
  }

  render() {
    return html`
      ${this.content}
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-block__heading`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSContentBlockHeading;
