/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { html, property, customElement, LitElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import styles from './content-item-horizontal.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The eyebrow content of content item horizontal.
 *
 * @element dds-content-item-horizontal-eyebrow
 */
@customElement(`${ddsPrefix}-content-item-horizontal-eyebrow`)
class DDSContentItemHorizontalEyebrow extends LitElement {
  /**
   * The shadow slot this eyebrow content should be in.
   */
  @property({ reflect: true })
  slot = 'eyebrow';

  render() {
    return html`
      <slot></slot>
    `;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static styles = styles;
}

export default DDSContentItemHorizontalEyebrow;
