/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import DDSContentBlockV2 from '../content-block-v2/content-block';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './content-group.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content group.
 *
 * @abstract
 */
@customElement(`${ddsPrefix}-content-group-v2`)
class DDSContentGroupV2 extends StableSelectorMixin(DDSContentBlockV2) {
  // protected _renderInnerBody(): TemplateResult | string | void {
  //   return html` ${this._renderMedia()}${this._renderContent()} `;
  // }

  static get stableSelector() {
    return `${ddsPrefix}--content-group-v2`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSContentGroupV2;
