/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import settings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import C4DButtonGroup from '../button-group/button-group';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './leadspace-block.scss';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';

const { stablePrefix: c4dPrefix } = settings;

/**
 * LeadSpace Block cta.
 *
 * @element c4d-leadspace-block-cta
 */
@customElement(`${c4dPrefix}-leadspace-block-cta`)
class C4DLeadSpaceBlockCTA extends StableSelectorMixin(C4DButtonGroup) {
  static get stableSelector() {
    return `${c4dPrefix}--leadspace-block__cta`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default C4DLeadSpaceBlockCTA;
