/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { DDSButtonGroupBase } from '../button-group/button-group';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './leadspace-block.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * LeadSpace Block cta.
 *
 * @element dds-leadspace-block-cta
 */
@customElement(`${ddsPrefix}-leadspace-block-cta`)
class DDSLeadSpaceBlockCTA extends StableSelectorMixin(DDSButtonGroupBase) {
  static get stableSelector() {
    return `${ddsPrefix}--leadspace-block__cta`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSLeadSpaceBlockCTA;
