/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css, customElement, html } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import DDSContentBlock from '../content-block/content-block';
import styles from './leadspace-block.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * LeadSpace Block content Component.
 *
 * @element dds-leadspace-block-content
 */
@customElement(`${ddsPrefix}-leadspace-block-content`)
class DDSLeadSpaceBlockContent extends DDSContentBlock {
  render() {
    return html`
      <slot name="heading"></slot>
      ${this._renderBody()}
    `;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSLeadSpaceBlockContent;
