/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import DDSImage from '../image/image';
import styles from './cta.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Card CTA Image.
 *
 * @element dds-card-cta-image
 */
class DDSCardCTAImage extends DDSImage {
  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

if (!customElements.get(`${ddsPrefix}-card-cta-image`)) {
  customElements.define(`${ddsPrefix}-card-cta-image`, DDSCardCTAImage);
}

export default DDSCardCTAImage;
