/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css, customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import DDSTextCTA from './text-cta';
import styles from '../link-list/link-list.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Link list item CTA.
 *
 * @element dds-link-list-item-cta
 */
@customElement(`${ddsPrefix}-link-list-item-cta`)
class DDSLinkListItemCTA extends DDSTextCTA {
  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'listitem');
    }
    super.connectedCallback();
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSLinkListItemCTA;
