/**
 * @license
 *
 * Copyright IBM Corp. 2021, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import settings from '../../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './cloud-masthead.scss';
import C4DMastheadGlobalBar from '../masthead-global-bar';
import { carbonElement as customElement } from '../../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';

const { stablePrefix: c4dPrefix } = settings;

/**
 * The action bar in Cloud masthead.
 *
 * @element c4d-cloud-masthead-global-bar
 */
@customElement(`${c4dPrefix}-cloud-masthead-global-bar`)
class C4DCloudMastheadGlobalBar extends C4DMastheadGlobalBar {
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default C4DCloudMastheadGlobalBar;
