/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import BXLink from '../../../internal/vendor/@carbon/web-components/components/link/link.js';
import ddsSettings from '../../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './cloud-masthead.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Cloud MegaMenu category link
 *
 * @element dds-cloud-megamenu-category-link
 */
@customElement(`${ddsPrefix}-cloud-megamenu-category-link`)
class DDSCloudMegaMenuCateoryLink extends BXLink {
  /**
   * link title.
   */
  @property({ reflect: true })
  title = '';

  /**
   * @returns The inner content.
   */
  protected _renderInner() {
    const { title } = this;
    return html`
      <p>${title}</p>
      <span><slot></slot></span>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSCloudMegaMenuCateoryLink;
