/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import BXSideNavLink from 'carbon-web-components/es/components/ui-shell/side-nav-link.js';
import styles from './cloud-masthead.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Cloud-specific masthead left nav item.
 *
 * @element dds-cloud-left-nav-item
 */
@customElement(`${ddsPrefix}-cloud-left-nav-item`)
class DDSCloudLeftNavItem extends BXSideNavLink {
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSCloudLeftNavItem;
