/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import CDSSideNavLink from '@carbon/web-components/es/components/ui-shell/side-nav-link.js';
import settings from '../../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './cloud-masthead.scss?lit';
import { carbonElement as customElement } from '../../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element.js';

const { stablePrefix: c4dPrefix } = settings;

/**
 * Cloud-specific masthead left nav item.
 *
 * @element c4d-cloud-left-nav-item
 */
@customElement(`${c4dPrefix}-cloud-left-nav-item`)
class C4DCloudLeftNavItem extends CDSSideNavLink {
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default C4DCloudLeftNavItem;
