/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { css } from 'lit-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { carbonElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';
import DDSLinkWithIcon from '../link-with-icon/link-with-icon';
import styles from './quote.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Quote link with item
 *
 * @element dds-quote-link-with-icon
 */
@carbonElement(`${ddsPrefix}-quote-link-with-icon`)
class DDSQuoteLinkWithIcon extends DDSLinkWithIcon {
  static get stableSelector() {
    return `${ddsPrefix}--quote-link-with-icon`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSQuoteLinkWithIcon;
