/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { unsafeHTML } from 'lit-html/directives/unsafe-html';
import { html, property, customElement, LitElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import markdownToHtml from '@carbon/ibmdotcom-utilities/es/utilities/markdownToHtml/markdownToHtml.js';
import styles from './markdown.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Markdown content.
 *
 * @element dds-markdown
 */
@customElement(`${ddsPrefix}-markdown`)
class DDSMarkdown extends LitElement {
  /**
   * The markdown content.
   */
  @property()
  content = '';

  /**
   * `true` to avoid using bold style.
   */
  @property({ type: Boolean, attribute: 'no-bold' })
  noBold = false;

  /**
   * `true` to avoid using creating paragraphs.
   */
  @property({ type: Boolean, attribute: 'no-create-paragraphs' })
  noCreateParagraphs = true;

  render() {
    const { noBold, content, noCreateParagraphs } = this;
    return html`
      ${unsafeHTML(markdownToHtml(content, { bold: !noBold, createParagraphs: !noCreateParagraphs, cleanString: true }))}
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSMarkdown;
