/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, property } from 'lit/decorators.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSMarkdown from '../markdown/markdown';
import './content-group-paragraph';
import styles from './content-group.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The copy content in content group.
 *
 * @element dds-content-group-copy
 */
@customElement(`${ddsPrefix}-content-group-copy`)
class DDSContentGroupCopy extends StableSelectorMixin(DDSMarkdown) {
  protected get _customTags() {
    const tags = new Set(super._customTags);
    tags.add(`${ddsPrefix}-content-group-paragraph`);
    return tags;
  }

  protected get _renderer() {
    return Object.assign(super._renderer, {
      paragraph(text) {
        return `<${ddsPrefix}-content-group-paragraph>${text}</${ddsPrefix}-content-group-paragraph>`;
      },
    });
  }

  /**
   * The shadow slot this copy content should be in.
   */
  @property({ reflect: true })
  slot = 'copy';

  static get stableSelector() {
    return `${ddsPrefix}--content-group__copy`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSContentGroupCopy;
