/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, css, customElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSContentBlock from '../content-block/content-block';
import styles from './content-block-simple.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Simple version of content block.
 *
 * @element dds-content-block-simple
 * @slot media - The media content.
 */
@customElement(`${ddsPrefix}-content-block-simple`)
class DDSContentBlockSimple extends StableSelectorMixin(DDSContentBlock) {
  // eslint-disable-next-line class-methods-use-this
  protected _renderContent() {
    // Renders `<div class="bx--content-item">` directly instead of using `<dds-content-item>`
    // because `<dds-content-block-simple>` uses only the copy content
    return html`
      <div class="${prefix}--content-block__children">
        <div class="${prefix}--content-block-simple__content">
          <div class="${prefix}--content-item">
            <slot></slot>
          </div>
          <div>
            <slot name="media"></slot>
          </div>
        </div>
      </div>
    `;
  }

  // eslint-disable-next-line class-methods-use-this
  protected _renderCopy() {
    return '';
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-block-simple`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSContentBlockSimple;
