/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css, customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import DDSCardLink from '../card-link/card-link';
import styles from './feature-section.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Feature Section Card Link.
 *
 * @element dds-feature-section-card-link
 */
@customElement(`${ddsPrefix}-feature-section-card-link`)
class DDSFeatureSectionCardLink extends DDSCardLink {
  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'listitem');
    }
    super.connectedCallback();
  }

  static get stableSelector() {
    return `${ddsPrefix}--feature-section-card-link`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSFeatureSectionCardLink;
