/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, customElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import styles from '@carbon/ibmdotcom-styles/scss/components/link-with-icon/_link-with-icon.scss';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import DDSLink from '../../globals/internal/link';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Link with icon.
 *
 * @element dds-link-with-icon
 */
@customElement(`${ddsPrefix}-link-with-icon`)
class DDSLinkWithIcon extends DDSLink {
  // eslint-disable-next-line class-methods-use-this
  protected _renderInner() {
    return html`
      <span><slot></slot></span>
      <slot name="icon"></slot>
    `;
  }

  updated() {
    const { disabled, _linkNode: linkNode } = this;
    if (linkNode) {
      linkNode.classList.add(`${prefix}--link-with-icon`);
      linkNode.classList.toggle(`${prefix}--link--disabled`, disabled);
    }
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLinkWithIcon;
