name: Contribution Request 💓
description:
  Contribute things large and small — code, design, ideas, and guidance.
title: '[YOUR TITLE]: Brief description'
assignees:
  - jeffchew,ljcarot,oliviaflory,RichKummer,IgnacioBecerra
labels: ['contribution']
body:
  - type: markdown
    attributes:
      value: '## Contribution Request 💓'
  - type: markdown
    attributes:
      value: 'Thank you for contributing to Carbon for IBM.com. Before you submit your contribution, please visit the [Contribution section](https://www.ibm.com/standards/carbon/contributing/overview/) on our website to understand the process and requirements.'
  - type: dropdown
    id: contribution-type
    attributes:
      label: Contribution type
      options:
        - Documentation
        - Components
        - Patterns
        - Other
    validations:
      required: true
  - type: textarea
    id: contribution-type-other
    attributes:
      label: Contribution type (other)
      description: "If you selected 'Other', please describe below."
  - type: textarea
    id: intent
    attributes:
      label: Intent
      description: "A clear and concise description of what the need or user problem this new contribution is trying to meet or solve (ex. I'm always frustrated when...)."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: "A clear and concise description of what you want your contribution to happen

Please add any supporting or required documentations here with a short description to help us get started with your contribution inquiry (ex. Design spec document.)

- For Documentation contribution, please visit the [Documentation contribution website page](https://www.ibm.com/standards/carbon/contributions/documentation/) for detail on what information you need to provide.

- For Components contribution, please visit the [Components contribution website page](https://www.ibm.com/standards/carbon/contributing/components) for detail on what information you need to provide.

- For Patterns contribution, please visit the [Patterns contribution website page](https://www.ibm.com/standards/carbon/contributing/patterns) for detail on what information you need to provide."
    validations:
      required: true
  - type: textarea
    id: organization
    attributes:
      label: 'IBM Organization or Company you are part of'
      description: "Please let us know which IBM Organization or Company you are part of or any additional information that can help us collaborate with you better, and reach out to us on Slack at #carbon-for-ibm-dotcom and provide us the link to this contribution request issue."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
            Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
        - label:
            I checked the [current
            issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for
            duplicate issues
