name: Feature Request 💡
description:
  Suggest a new idea for the project.
title: '[YOUR TITLE]: Brief description'
assignees:
  - jeffchew,ljcarot,shixiedesign,RobertaJHahn,skuruvil,annawen1,BrunnoM7
labels: ['Feature request']
body:
  - type: markdown
    attributes:
      value: '## Feature Request 💡'
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: "A clear and concise description of what the problem this new feature is trying to solve. (ex. I'm always frustrated when...)"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: The solution
      description: "A clear and concise description of what you want to happen"
    validations:
      required: true
  - type: textarea
    id: user-research
    attributes:
      label: User research
  - type: textarea
    id: user-insights
    attributes:
      label: User insights
  - type: textarea
    id: user-metrics
    attributes:
      label: User metrics
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
            Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
          required: true
        - label:
            I checked the [current
            issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for
            duplicate issues
