name: (C4IBM.com team only) Test Scenario Creation
description:
  Describe the test scenario that will need to be created in e2e tests
title: '[Test Scenario]: Component and test scenario title'
labels: ['dev','test: e2e']
body:
  - type: input
    id: component
    attributes:
      label: Component and test scenario title
    validations:
      required: true
  - type: textarea
    id: scenario
    attributes:
      label: Test scenario steps
      value: "1.

2.

3."
    validations:
      required: true
