/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, LitElement } from 'lit';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { prefix } from '../../globals/settings';
import styles from './toggletip.scss';

/**
 * Toggletip button.
 */
@customElement(`${prefix}-toggletip-button`)
class CDSToggleTipButton extends LitElement {
  render() {
    return html` <button aria-controls="${this.id}">
      <slot></slot>
    </button>`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSToggleTipButton;
