/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import { classMap } from 'lit-html/directives/class-map.js';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import { FOOTER_SIZE } from './defs';
import styles from './footer.scss';

export { FOOTER_SIZE };

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The top-level element in footer.
 *
 * @element dds-footer
 * @slot brand - The brand content.
 * @slot legal-nav - The legal nav content.
 * @slot locale-button - The locale button content.
 */
@customElement(`${ddsPrefix}-footer`)
class DDSFooter extends StableSelectorMixin(LitElement) {
  /**
   * Footer size.
   */
  @property({ reflect: true })
  size = FOOTER_SIZE.REGULAR;

  /**
   * Update the CSS selectors depending on the locale button being rendered or not.
   */
  @property({ type: Boolean, attribute: 'disable-locale-button' })
  disableLocaleButton = false;

  connectedCallback() {
    this.setAttribute('role', 'contentinfo');

    if (!this.hasAttribute('aria-label')) {
      this.setAttribute('aria-label', 'footer');
    }
    super.connectedCallback();
  }

  render() {
    const { disableLocaleButton } = this;

    const classes = {
      [`${prefix}--footer__logo-container`]: true,
      [`${prefix}--footer__locale-button--disabled`]: disableLocaleButton,
    };

    return html`
      <section class="${prefix}--footer__main">
        <div class="${prefix}--footer__main-container">
          <div class=${classMap(classes)}>
            <div class="${prefix}--footer__logo-row">
              <slot name="brand"></slot>
              <slot name="locale-button"></slot>
              <slot name="language-selector"></slot>
            </div>
          </div>
          <slot></slot>
        </div>
      </section>
      <slot name="legal-nav"></slot>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--footer`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSFooter;
