/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import FocusMixin from 'carbon-web-components/es/globals/mixins/focus.js';
import { FOOTER_SIZE } from './footer';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './footer.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Language selector
 *
 * @element dds-language-selector
 */
@customElement(`${ddsPrefix}-language-selector-item`)
class DDSLanguageSelectorItem extends StableSelectorMixin(FocusMixin(LitElement)) {
    
  /**
   * Button label for accessibility.
   */
  @property()
  buttonLabel = 'Select geographic area';

  /**
   * Property to hide close button.
   */
  @property()
  hover = false;

  /**
   * Size property to apply different styles.
   */
  @property()
  size = FOOTER_SIZE.REGULAR;

  private test(e) {
    //console.log(this.hover)
    this.hover = true;
  }

  render() {
    return html`
        <div tabindex="-1" class="bx--language-selector__menu-item-open">
            <slot></slot>
        </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--language-selector-item`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLanguageSelectorItem;
