/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import FocusMixin from 'carbon-web-components/es/globals/mixins/focus';
import EarthFilled20 from 'carbon-web-components/es/icons/earth--filled/20';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import '../locale-modal/locale-modal-container';
import styles from './footer.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Locale button.
 *
 * @element dds-locale-button
 */
@customElement(`${ddsPrefix}-locale-button`)
class DDSLocaleButton extends StableSelectorMixin(FocusMixin(LitElement)) {
  /**
   * The shadow slot this locale button should be in.
   */
  @property({ reflect: true })
  slot = 'locale-button';

  createRenderRoot() {
    return this.attachShadow({ mode: 'open', delegatesFocus: true });
  }

  render() {
    return html`
      <button id="button" class="${prefix}--btn ${prefix}--btn--secondary ${prefix}--locale-btn">
        <slot></slot>
        ${EarthFilled20()}
      </button>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--locale-btn`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLocaleButton;
