/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { html, property, LitElement } from 'lit-element/lit-element';
import { carbonElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './card.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The eyebrow content of card.
 *
 * @element dds-card-eyebrow
 */
@carbonElement(`${ddsPrefix}-card-eyebrow`)
class DDSCardEyebrow extends StableSelectorMixin(LitElement) {
  /**
   * The shadow slot this card eyebrow should be in.
   */
  @property({ reflect: true })
  slot = 'eyebrow';

  render() {
    return html` <slot></slot> `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--card-eyebrow`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static styles = styles;
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSCardEyebrow;
