/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import BXModalHeading from 'carbon-web-components/es/components/modal/modal-heading.js';
import styles from './leaving-ibm.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Leaving Ibm modal heading.
 *
 * @element dds-leaving-ibm-modal-heading
 */
@customElement(`${ddsPrefix}-leaving-ibm-modal-heading`)
class DDSLeavingIbmModalHeading extends BXModalHeading {
  connectedCallback() {
    if (!this.hasAttribute('id')) {
      this.setAttribute('id', 'leaving-ibm-heading');
    }
    super.connectedCallback();
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLeavingIbmModalHeading;
