/**
 * @license
 *
 * Copyright IBM Corp. 2021, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { html, property, customElement, LitElement } from 'lit-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './leaving-ibm.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The supplemental content of leaving IBM modal.
 *
 * @element dds-leaving-ibm-modal-supplemental
 */
@customElement(`${ddsPrefix}-leaving-ibm-modal-supplemental`)
class DDSLeavingIbmModalSupplemental extends StableSelectorMixin(LitElement) {
  /**
   * The shadow slot this supplemental content should be in.
   */
  @property({ reflect: true })
  slot = 'supplemental';

  render() {
    return html` <slot></slot> `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--leaving-ibm-modal-supplemental`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static styles = styles;
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSLeavingIbmModalSupplemental;
