/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import { LeavingIBMLabels, MiscLabels, Translation } from '../../../../services-store/src/types/translateAPI';
import './leaving-ibm-modal';
import 'carbon-web-components/es/components/modal/modal-body';
import 'carbon-web-components/es/components/modal/modal-header';
import 'carbon-web-components/es/components/modal/modal-heading';
import 'carbon-web-components/es/components/modal/modal-close-button';
import 'carbon-web-components/es/components/button/button';
import styles from './leaving-ibm.scss';

export { MODAL_SIZE } from 'carbon-web-components/es/components/modal/modal.js';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Component that rendres leaving IBM component labels.
 *
 * @element dds-leaving-ibm-composite
 */
@customElement(`${ddsPrefix}-leaving-ibm-composite`)
class DDSLeavingIbmComposite extends LitElement {
  /**
   * The placeholder for `setLanguage()` Redux action that will be mixed in.
   *
   * @internal
   */
  _setLanguage?: (string) => void;

  /**
   * The placeholder for `loadTranslation()` Redux action that will be mixed in.
   *
   * @internal
   */
  _loadTranslation?: (language?: string) => Promise<Translation>;

  /**
   * Leaving IBM modal copy
   */
  @property({ attribute: false })
  leavingIbmCopy: LeavingIBMLabels;

  /**
   * Leaving IBM modal button label
   */
  @property({ attribute: false })
  leavingIbmButtonLabel: MiscLabels;

  /**
   * The language used for query.
   */
  @property()
  language?: string;

  /**
   * `true` to open the search dropdown.
   */
  @property({ type: Boolean, reflect: true })
  open = false;

  firstUpdated() {
    const { language } = this;
    if (language) {
      this._setLanguage?.(language);
    }
    this._loadTranslation?.(language).catch(() => {}); // The error is logged in the Redux store
  }

  updated(changedProperties) {
    if (changedProperties.has('language')) {
      const { language } = this;
      if (language) {
        this._setLanguage?.(language);
      }
    }
  }

  render() {
    const { open } = this;
    return html`
      <dds-leaving-ibm-modal open="${open}" size="sm">
        <bx-modal-header>
          <bx-modal-close-button></bx-modal-close-button>
          <bx-modal-heading>Leaving the IBM web site</bx-modal-heading>
        </bx-modal-header>
        <bx-modal-body
          ><p>
            You are now leaving IBM.com and going to an external 3rd party site. Unless otherwise stated, the 3rd party's site
            Terms and Privacy Policy will apply, and may differ from IBM's.
          </p>
          <a href="https://www.ibm.com">ibm.com</a></bx-modal-body
        >
        <bx-modal-footer>
          <bx-btn kind="primary">Continue</bx-btn>
        </bx-modal-footer>
      </dds-leaving-ibm-modal>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLeavingIbmComposite;
