/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { css } from 'lit';
import { customElement } from 'lit/decorators.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSMarkdown from '../markdown/markdown';
import './content-item-paragraph';
import styles from './content-item.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The copy content of content item.
 *
 * @element dds-content-item-copy
 */
@customElement(`${ddsPrefix}-content-item-copy`)
class DDSContentItemCopy extends StableSelectorMixin(DDSMarkdown) {
  protected get _customTags() {
    const tags = new Set(super._customTags);
    tags.add(`${ddsPrefix}-content-item-paragraph`);
    return tags;
  }

  protected get _renderer() {
    this.childNodes.forEach((node) => {
      if (node.nodeType === Node.TEXT_NODE) {
        this.removeChild(node);
      }
    });

    return Object.assign(super._renderer, {
      paragraph(text) {
        return `<${ddsPrefix}-content-item-paragraph>${text}</${ddsPrefix}-content-item-paragraph>`;
      },
    });
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-item__copy`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSContentItemCopy;
