/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, internalProperty, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import ifNonNull from 'carbon-web-components/es/globals/directives/if-non-null.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import '../markdown/markdown';
import styles from './content-item.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The table mapping slot name with the private property name that indicates the existence of the slot content.
 */
const slotExistencePropertyNames = {
  cta: '_hasCta',
};

/**
 * Content item.
 *
 * @element dds-content-item
 */
@customElement(`${ddsPrefix}-content-item`)
class DDSContentItem extends StableSelectorMixin(LitElement) {
  /**
   * `true` if there is a CTA content.
   */
  @internalProperty()
  _hasCta = false;

  /**
   * Handles `slotchange` event on the CTA slot.
   *
   * @param event The event.
   */
  private _handleSlotchange({ target }: Event) {
    const { name } = target as HTMLSlotElement;
    const hasContent = (target as HTMLSlotElement)
      .assignedNodes()
      .some(node => node.nodeType !== Node.TEXT_NODE || node!.textContent!.trim());
    this[slotExistencePropertyNames[name] || '_hasDefaultContent'] = hasContent;
  }

  /**
   * Link `href`.
   */
  @property()
  copy = '';

  render() {
    const { copy, _hasCta: hasCta } = this;
    return html`
      <slot name="heading"></slot>
      <div>
        <slot name="media"></slot>
      </div>
      ${!copy
        ? undefined
        : html`
            <dds-markdown class="${prefix}--content-item__copy" nobold .content="${ifNonNull(copy)}"> </dds-markdown>
          `}
      <div ?hidden="${!hasCta}" class="${prefix}--content-item__cta">
        <slot name="cta" @slotchange="${this._handleSlotchange}"></slot>
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-item`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSContentItem;
