/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, customElement, LitElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import styles from './content-item.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The paragraph content in content item.
 *
 * @element dds-content-item-paragraph
 */
@customElement(`${ddsPrefix}-content-item-paragraph`)
class DDSContentItemParagraph extends StableSelectorMixin(LitElement) {
  static get stableSelector() {
    return `${ddsPrefix}--content-item-paragraph`;
  }

  render() {
    return html`
      <slot></slot>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSContentItemParagraph;
