/**
 * * @license
 *
 * Copyright IBM Corp. 2019, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { html, property, customElement, LitElement, query } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import settings from 'carbon-components/es/globals/js/settings';
import styles from './structured-list.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSStructuredListRow from './structured-list-row';
import { elementType } from 'prop-types';

const { stablePrefix: ddsPrefix } = ddsSettings;
const { prefix } = settings;

type TableHeader = 'col' | 'row' | false;

/**
 * StructuredList
 *
 * @element dds-structured-list
 */
@customElement(`${ddsPrefix}-structured-list`)
class DDSStructuredList extends StableSelectorMixin(LitElement) {
  _rows: DDSStructuredListRow[] = [];

  _headerRows: DDSStructuredListRow[] = [];

  _bodyRows: DDSStructuredListRow[] = [];

  _footerRows: DDSStructuredListRow[] = [];

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'table');
    }
    this._handleSlotChange();
    super.connectedCallback();
  }

  _handleSlotChange() {
    const rows = Array.from(this.children).filter(element => {
      return element instanceof DDSStructuredListRow;
    }) as [DDSStructuredListRow] | [];

    this._rows = rows;

    this._headerRows = rows!.filter(row => row!.slot === 'header');

    this._bodyRows = rows!.filter(row => !['header', 'footer'].includes(row.slot));

    this._footerRows = rows!.filter(row => row!.slot === 'footer');

    this.requestUpdate();
  }

  _renderTableHeader() {
    const { _headerRows: headerRows } = this;

    return headerRows.length > 0
      ? html`
          <div class="${prefix}--structured-list-head" role="rowgroup">
            <slot name="header"></slot>
          </div>
        `
      : '';
  }

  _renderTableBody() {
    const { _bodyRows: bodyRows } = this;

    return bodyRows.length > 0
      ? html`
          <div class="${prefix}--structured-list-body" role="rowgroup">
            <slot></slot>
          </div>
        `
      : '';
  }

  _renderTableFooter() {
    const { _footerRows: footerRows } = this;

    return footerRows.length > 0
      ? html`
          <div class="${prefix}--structured-list-foot" role="rowgroup">
            <slot name="footer"></slot>
          </div>
        `
      : '';
  }

  render() {
    const { _handleSlotChange: handleSlotChange } = this;

    return html`
      <section @slotchange="${handleSlotChange}" class="${prefix}--structured-list">
        ${this._renderTableHeader()} ${this._renderTableBody()} ${this._renderTableFooter()}
      </section>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--structured-list`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSStructuredList;
