/**
 * * @license
 *
 * Copyright IBM Corp. 2019, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { html, property, customElement, LitElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import settings from 'carbon-components/es/globals/js/settings';
import styles from './structured-list.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSStructuredListRow from './structured-list-row';

const { stablePrefix: ddsPrefix } = ddsSettings;
const { prefix } = settings;

/**
 * StructuredListCell
 *
 * @element dds-structured-list-cell
 */
@customElement(`${ddsPrefix}-structured-list-cell`)
class DDSStructuredListCell extends StableSelectorMixin(LitElement) {
  _parentRow: DDSStructuredListRow | null = null;

  connectedCallback() {
    const parentRow = this.closest(`${ddsPrefix}-structured-list-row`) as DDSStructuredListRow;
    this._parentRow = parentRow;

    if (!this.hasAttribute('role')) {
      if (parentRow.slot === 'header') {
        this.setAttribute('role', 'columnheader');
      } else {
        this.setAttribute('role', 'cell');
      }
    }

    super.connectedCallback();
  }

  render() {
    return html`
      <slot></slot>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--structured-list`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSStructuredListCell;
