/**
 * * @license
 *
 * Copyright IBM Corp. 2019, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { html, property, customElement, LitElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import styles from './structured-list.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSStructuredListRow from './structured-list-row';
import DDSStructuredList from './structured-list';
import DDSStructuredListGroup from './structured-list-group';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * StructuredListCell
 *
 * @element dds-structured-list-cell
 */
@customElement(`${ddsPrefix}-structured-list-cell`)
class DDSStructuredListCell extends StableSelectorMixin(LitElement) {
  _parentRow: DDSStructuredListRow | null = this.closest(`${ddsPrefix}-structured-list-row`);

  _parentGroup: DDSStructuredListGroup | null = this.closest(`${ddsPrefix}-structured-list-group`);

  _parentTable: DDSStructuredList | null = this.closest(`${ddsPrefix}-structured-list`);

  @property({ reflect: true, attribute: 'labels' })
  _headerScope: string | null = null;

  @property({ attribute: 'aria-label', reflect: true })
  _groupLabel: string | null = null;

  connectedCallback() {
    const { _headerScope: headerScope, _parentRow: parentRow } = this;

    if (!this.hasAttribute('role')) {
      if (headerScope) {
        let role;
        switch (headerScope.toLowerCase()) {
          case 'row':
            role = 'rowheader';
            break;

          case 'column':
            role = 'columnheader';
            break;

          default:
            role = 'cell';
            break;
        }
        this.setAttribute('role', role);
      } else if (parentRow!.slot === 'header') {
        this.setAttribute('role', 'columnheader');
      } else {
        this.setAttribute('role', 'cell');
      }
    }

    this._groupLabel = this._parentGroup?.groupTitle || null;

    super.connectedCallback();
  }

  render() {
    return html`
      <slot></slot>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSStructuredListCell;
