/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import deprecate from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/deprecate/deprecate';
import settings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

import styles from './card-section-images.scss';
import C4DContentSection from '../content-section/content-section';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';

const { stablePrefix: c4dPrefix } = settings;

/**
 * The Card Section Images pattern
 *
 * @element c4d-card-section-images
 */
@customElement(`${c4dPrefix}-card-section-images`)
class C4DCardSectionImages extends StableSelectorMixin(C4DContentSection) {
  static get stableSelector() {
    return `${c4dPrefix}--card-section-images`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default deprecate(
  /* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
  C4DCardSectionImages,
  'The c4d-card-section-images component has been merged with the c4d-card-section component ' +
    'See c4d-card-section documentation for more information.'
);
