/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css } from 'lit';
import { customElement } from 'lit/decorators.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import deprecate from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/deprecate/deprecate';
import DDSContentBlock from '../content-block/content-block';
import styles from './content-block-mixed.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content block mixed
 *
 * @element dds-content-block-mixed
 */
@customElement(`${ddsPrefix}-content-block-mixed`)
class DDSContentBlockMixed extends DDSContentBlock {
  static get stableSelector() {
    return `${ddsPrefix}--content-block-mixed`;
  }

  // `styles` here is a `CSSResult` generated by custom WepPack loader
  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default deprecate(
  DDSContentBlockMixed,
  'The content-block-mixed component has been deprecated in favor of the content-section/block, video-player/image, pictogram-items, and other content-group components. ' +
    'See content-block/section documentation for more information.'
);
