/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { property, customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import BXSideNavMenuItem from 'carbon-custom-elements/es/components/ui-shell/side-nav-menu-item';
import styles from './masthead.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Masthead left nav submenu item.
 *
 * @element dds-left-nav-menu-item
 */
@customElement(`${ddsPrefix}-left-nav-menu-item`)
class DDSLeftNavMenuItem extends BXSideNavMenuItem {
  /**
   * The title.
   */
  @property()
  title = '';

  updated() {
    this.shadowRoot!.querySelector('slot:not([name])')!.textContent = this.title;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLeftNavMenuItem;
