/**
 * @license
 *
 * Copyright IBM Corp. 2022, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import settings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import ArrowRight16 from '../../internal/vendor/@carbon/web-components/icons/arrow--right/16.js';
import BXSideNavMenuItem from '@carbon/web-components/es/components/ui-shell/side-nav-menu-item.js';
import styles from './masthead.scss?lit';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';

const { prefix, stablePrefix: c4dPrefix } = settings;

/**
 * Masthead left nav CTA item.
 *
 * @element c4d-left-nav-cta-item
 */
@customElement(`${c4dPrefix}-left-nav-cta-item`)
class C4DLeftNavCtaItem extends BXSideNavMenuItem {
  render() {
    const { href, title } = this;
    return html`
      <a part="link" class="${prefix}--side-nav__link" href="${href}">
        <div part="title" class="${prefix}--side-nav__link-text">
          <span><slot>${title}</slot></span>
          ${ArrowRight16()}
        </div>
      </a>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default C4DLeftNavCtaItem;
