/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import DDSLeftNavMenu from './left-nav-menu';
import styles from './masthead.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Masthead left nav submenu item.
 *
 * @element dds-left-nav-menu-item
 */
@customElement(`${ddsPrefix}-left-nav-menu-highlighted`)
class DDSLeftNavMenuHighlighted extends DDSLeftNavMenu {
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLeftNavMenuHighlighted;
