/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, internalProperty, property, customElement } from 'lit-element';
import { breakpoints } from '@carbon/layout/es';
import HostListener from 'carbon-web-components/es/globals/decorators/host-listener.js';
import HostListenerMixin from 'carbon-web-components/es/globals/mixins/host-listener.js';
import on from 'carbon-components/es/globals/js/misc/on';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import FocusMixin from 'carbon-web-components/es/globals/mixins/focus.js';
import DDSIcon from '../icon/icon';
import Handle from '../../globals/internal/handle';
import styles from './masthead.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The IBM logo UI in masthead.
 *
 * @element dds-masthead-logo
 */
@customElement(`${ddsPrefix}-masthead-logo`)
class DDSMastheadLogo extends FocusMixin(HostListenerMixin(DDSIcon)) {
  /**
   * Media query listener handler.
   */
  private _mqHandler: Handle | null = null;

  /**
   * Link `href`.
   */
  @property()
  href = 'https://www.ibm.com/';

  /**
   * The shadow slot this logo UI should be in.
   */
  @property({ reflect: true })
  slot = 'brand';

  /**
   * Search bar opened flag.
   */
  @internalProperty()
  private _openedSearch = false;

  /**
   * Large breakpoint flag.
   */
  @internalProperty()
  private _responsiveLg = false;

  /**
   * Handles toggle event from the search component.
   *
   * @param event The event.
   */
  @HostListener('parentRoot:eventToggleSerch')
  // @ts-ignore: The decorator refers to this method but TS thinks this method is not referred to
  private _handleSearchToggle = (event: Event) => {
    this._openedSearch = (event as CustomEvent).detail.active;
  };

  /**
   * Handles media query event.
   *
   * @param event The event.
   */
  private _handleMediaQuery(event: Event) {
    this._responsiveLg = (event as MediaQueryListEvent).matches;
  }

  createRenderRoot() {
    return this.attachShadow({ mode: 'open', delegatesFocus: true });
  }

  connectedCallback() {
    super.connectedCallback();

    const mqLarge = this.ownerDocument?.defaultView?.matchMedia(`(max-width: ${breakpoints.lg.width})`);
    this._responsiveLg = mqLarge ? mqLarge.matches : false;

    this._mqHandler = on(mqLarge, 'change', this._handleMediaQuery.bind(this));
  }

  disconnectedCallback() {
    if (this._mqHandler) {
      this._mqHandler = this._mqHandler.release();
    }

    super.disconnectedCallback();
  }

  render() {
    return this._openedSearch && this._responsiveLg ? html`` : super.render();
  }

  /**
   * The name of the custom event fired after the seach is toggled.
   */
  static get eventToggleSerch() {
    return `${ddsPrefix}-masthead-search-toggled`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSMastheadLogo;
