/**
 * @license
 *
 * Copyright IBM Corp. 2022, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { ifDefined } from 'lit-html/directives/if-defined.js';
import { html, customElement, property } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings.js';
import Chat20 from '../../internal/vendor/@carbon/web-components/icons/chat/20.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './masthead.scss';
import DDSMastheadProfile from './masthead-profile';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The contact button UI in the masthead.
 *
 * @element dds-masthead-contact
 */
@customElement(`${ddsPrefix}-masthead-contact`)
class DDSMastheadContact extends DDSMastheadProfile {
  /**
   * The `aria-label` attribute for the trigger button.
   */
  @property({ attribute: 'trigger-label' })
  triggerLabel = 'Contact';

  /**
   * Handles events fired by CM_APP.
   *
   * @see DOCUMENT_EVENTS live-advisor/cm-app/js/helpers/otherConstants.js
   *   - https://github.ibm.com/live-advisor/cm-app/blob/master/js/helpers/otherConstants.js
   */
  protected _handleCMAppEvents(event: CustomEvent) {
    const { type } = event;

    switch (type) {
      case 'cm-app-pane-displayed':
        this.triggerLabel = 'Close contact window';
        break;

      case 'cm-app-pane-hidden':
        this.triggerLabel = 'Show contact window';
        break;

      default:
        break;
    }
  }

  connectedCallback() {
    const { _handleCMAppEvents: handleCMAppEvents } = this;
    super.connectedCallback();

    /**
     * TODO: Appease typescript compiler.
     *
     * These events are fired by live-advisor/cm-app, and are listened for on the document.
     * To get a reference back to the instance of `this` we have to bind it to the event handler.
     * This is currently not possible using the HostListener mixin & decorator.
     *
     * @see DOCUMENT_EVENTS live-advisor/cm-app/js/helpers/otherConstants.js
     *   - https://github.ibm.com/live-advisor/cm-app/blob/master/js/helpers/otherConstants.js
     */

    const CMEventHandler = handleCMAppEvents.bind(this);
    // @ts-ignore: custom events & CustomEvent listener.
    document.addEventListener('cm-app-pane-displayed', CMEventHandler);
    // @ts-ignore: custom events & CustomEvent listener.
    document.addEventListener('cm-app-pane-hidden', CMEventHandler);
  }

  render() {
    const { triggerLabel, _handleClick: handleClick } = this;
    return html`
      <a
        href="javascript:void 0"
        class="${prefix}--header__menu-item ${prefix}--header__menu-title"
        aria-label="${ifDefined(triggerLabel)}"
        @click=${handleClick}>
        ${Chat20()}
      </a>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSMastheadContact;
