/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, customElement, LitElement, property } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './masthead.scss';
import './top-nav';
import './top-nav-menu';
import './top-nav-menu-item';
import './top-nav-item';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Masthead.
 *
 * @element dds-masthead-l1
 * @slot brand - The left hand area.
 * @slot nav - The nav content.
 * @slot profile - The right hand area.
 */
@customElement(`${ddsPrefix}-masthead-l1`)
class DDSMastheadL1 extends StableSelectorMixin(LitElement) {
    @property({ attribute: 'l1-title', reflect: true })
    title = '';

    @property({ attribute: 'l1-title-href', reflect: true })
    titleHref = '';

    @property({ attribute: 'l1-items' })
    l1Items = [];

    _renderName() {
        return html`
            <div class="${prefix}--masthead__l1-name">
                <span class="${prefix}--masthead__l1-name-title">
                    <a href="${this.titleHref}">${this.title}</a>
                </span>
            </div>
        `;
    }

    _renderContentContainer() {
        return html`
            <div class="${prefix}--header__nav-container">
                <dds-top-nav>
                    <dds-top-nav-item>
                        Lorem Ipsum dolor
                    </dds-top-nav-item>
                </dds-top-nav>
            </div>
        `;
    }

    render() {
        return html`
        <div class="${prefix}--masthead__l1">
            ${this._renderName()}
            ${this._renderContentContainer()}
        </div>
        `
    }

    static get stableSelector() {
        return `${ddsPrefix}--masthead__l1`;
    }

    static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSMastheadL1;
