/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './masthead.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Masthead.
 *
 * @element dds-masthead-l1-name
 */
@customElement(`${ddsPrefix}-masthead-l1-name`)
class DDSMastheadL1Name extends StableSelectorMixin(LitElement) {
  /**
   * slot name for this component in the masthead l1
   */
  @property({ reflect: true })
  slot = 'name';

  @property({ reflect: true })
  url = '';

  @property({ reflect: true })
  title = '';

  render() {
    return html`
      <span class="${prefix}--masthead__l1-name-title">
        <a href="${this.url}">${this.title}</a>
      </span>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--masthead__l1-name`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSMastheadL1Name;
