/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement } from 'lit-element';
import { BXLinkBase } from '@carbon/web-components/es/components/link/link.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './masthead.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * MegaMenu category sublink
 *
 * @element dds-megamenu-category-link
 */
@customElement(`${ddsPrefix}-megamenu-category-link`)
class DDSMegaMenuCateoryLink extends BXLinkBase {
  /**
   * link title.
   */
  @property({ reflect: true })
  title = '';

  /**
   * @returns The inner content.
   */
  protected _renderInner() {
    const { title } = this;
    return html`
      <span>${title}</pan>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSMegaMenuCateoryLink;
