/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, customElement, LitElement, property } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './masthead.scss';
import './megamenu-category-heading';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * MegaMenu category group
 *
 * @element dds-megamenu-category-group
 */
@customElement(`${ddsPrefix}-megamenu-category-group`)
class DDSMegaMenuCategoryGroup extends LitElement {
  /**
   * href for the category group title
   */
  @property({ reflect: true })
  href = '';

  /**
   * category group title/heading
   */
  @property({ reflect: true })
  title = '';

  render() {
    return html`
      <div class="${prefix}--masthead__megamenu__category-group-shield">
        <div class="${prefix}--masthead__megamenu__category-group-content-wrapper">
          <div class="${prefix}--masthead__megamenu__category-group-heading">
            <slot name="heading"></slot>
          </div>
          <div class="${prefix}--masthead__megamenu__category-group-content">
            <slot></slot>
          </div">
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSMegaMenuCategoryGroup;
