/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, LitElement } from 'lit';
import { property } from 'lit/decorators.js';
import settings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './masthead.scss?lit';
import './megamenu-link-with-icon';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element.js';

const { prefix, stablePrefix: c4dPrefix } = settings;

/**
 * MegaMenu category group
 *
 * @element c4d-megamenu-category-group
 */
@customElement(`${c4dPrefix}-megamenu-category-group`)
class C4DMegaMenuCategoryGroup extends LitElement {
  /**
   * href for the category group title
   */
  @property({ reflect: true })
  href = '';

  /**
   * category group title/heading
   */
  @property({ reflect: true })
  title = '';

  render() {
    return html`
      <div class="${prefix}--masthead__megamenu__category-group-shield">
        <div
          class="${prefix}--masthead__megamenu__category-group-content-wrapper">
          <div class="${prefix}--masthead__megamenu__category-group-heading">
            <slot name="heading"></slot>
          </div>
          <div class="${prefix}--masthead__megamenu__category-group-content">
            <slot></slot>
          </div>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default C4DMegaMenuCategoryGroup;
