/**
 * @license
 *
 * Copyright IBM Corp. 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import ArrowRight20 from 'carbon-web-components/es/icons/arrow--right/20.js';
import styles from './masthead.scss';
import DDSMegaMenuHeading from './megamenu-heading';

/**
 * MegaMenu Category Heading.
 *
 * @element dds-megamenu-category-heading
 */
class DDSMegaMenuCategoryHeading extends DDSMegaMenuHeading {
  protected _arrowIcon = ArrowRight20();

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSMegaMenuCategoryHeading;
