/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import ArrowRight16 from 'carbon-web-components/es/icons/arrow--right/16.js';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './masthead.scss';
import '../link-with-icon/link-with-icon';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * MegaMenu
 *
 * @element dds-megamenu
 * @slot brand - The left hand area.
 * @slot nav - The nav content.
 * @slot profile - The right hand area.
 */
@customElement(`${ddsPrefix}-megamenu-right-navigation`)
class DDSMegaMenuRightNavigation extends StableSelectorMixin(LitElement) {
  /**
   * view all link href.
   */
  @property({ attribute: 'view-all-href', reflect: true })
  viewAllLinkHref = '';

  /**
   * view all link title.
   */
  @property({ attribute: 'view-all-title', reflect: true })
  viewAllLinkTitle = '';

  /**
   * autoid.
   */
  @property({ reflect: true })
  autoid = '';

  render() {
    return html`
      <div class="${prefix}--masthead__megamenu__categories-section">
        <div class="${prefix}--masthead__megamenu__categories">
          <slot></slot>
        </div>
        ${this.viewAllLinkHref &&
          html`
            <dds-link-with-icon
              href="${this.viewAllLinkHref}"
              class="${prefix}--masthead__megamenu__view-all-cta"
              data-autoid="${this.autoid}-view-all"
            >
              <span>${this.viewAllLinkTitle}</span>
              ${ArrowRight16({ slot: 'icon' })}
            </dds-link-with-icon>
          `}
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSMegaMenuRightNavigation;
