/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css, property } from 'lit-element';
import BXLink from '../../internal/vendor/@carbon/web-components/components/link/link.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { MEGAMENU_LINK_WITH_ICON_STYLE_SCHEME } from './defs';
import styles from './masthead.scss';
import { carbonElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element.js';

export { MEGAMENU_LINK_WITH_ICON_STYLE_SCHEME };

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Megamenu link with icon.
 *
 * @element dds-megamenu-link-with-icon
 */
@carbonElement(`${ddsPrefix}-megamenu-link-with-icon`)
class DDSMegaMenuLinkWithIcon extends BXLink {
  /**
   * link title.
   */
  @property({ reflect: true, attribute: 'style-scheme' })
  styleScheme = MEGAMENU_LINK_WITH_ICON_STYLE_SCHEME.DEFAULT;

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }
}

export default DDSMegaMenuLinkWithIcon;
