/**
 * @license
 *
 * Copyright IBM Corp. 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, customElement, LitElement, property } from 'lit-element';
import ArrowRight20 from 'carbon-web-components/es/icons/arrow--right/20.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './masthead.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * MegaMenu Category Heading.
 *
 * @element dds-megamenu-category-heading
 */
@customElement(`${ddsPrefix}-megamenu-category-heading`)
class DDSMegaMenuCategoryHeading extends LitElement {
  /**
   * href.
   */
  @property({ reflect: true })
  href = '';

  /**
   * Megamenu content category heading
   */
  @property({ reflect: true })
  title = '';

  render() {
    return html`
      <h2><a href="${this.href}">${this.title} ${ArrowRight20()}</a></h2>
      <span><slot></slot></span>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSMegaMenuCategoryHeading;
