/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, customElement, LitElement } from 'lit-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './masthead.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * MegaMenu left navigation (highlighted) section base class.
 */
export class DDSMegaMenuLeftNavigationBase extends LitElement {
  render() {
    return html` <slot></slot> `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/**
 * MegaMenu left navigation (highlighted) section.
 *
 * @element dds-megamenu-left-navigation
 */
@customElement(`${ddsPrefix}-megamenu-left-navigation`)
class DDSMegaMenuLeftNavigation extends DDSMegaMenuLeftNavigationBase {}

export default DDSMegaMenuLeftNavigation;
