/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, customElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ifNonNull from 'carbon-custom-elements/es/globals/directives/if-non-null';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import DDSMastheadTopNav from './top-nav';
import DDSLeftNavName from './left-nav-name';
import styles from './masthead.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The brand name UI in top nav.
 *
 * @element dds-top-nav-name
 */
@customElement(`${ddsPrefix}-top-nav-name`)
class DDSTopNavName extends DDSLeftNavName {
  connectedCallback() {
    super.connectedCallback();
    const { selectorTopNav } = this.constructor as typeof DDSTopNavName;
    const { nextElementSibling } = this;
    if (nextElementSibling && nextElementSibling.matches(selectorTopNav)) {
      (nextElementSibling as DDSMastheadTopNav).hideDivider = true;
    }
  }

  disconnectedCallback() {
    const { selectorTopNav } = this.constructor as typeof DDSTopNavName;
    const { nextElementSibling } = this;
    if (nextElementSibling && nextElementSibling.matches(selectorTopNav)) {
      (nextElementSibling as DDSMastheadTopNav).hideDivider = false;
    }
    super.disconnectedCallback();
  }

  render() {
    const { href, prefix: namePrefix } = this;
    const namePrefixPart = !namePrefix
      ? undefined
      : html`
          <span class="${prefix}--header__name--prefix">${namePrefix}</span>&nbsp;
        `;
    return html`
      <a class="${prefix}--header__name" href="${ifNonNull(href)}">${namePrefixPart}<slot></slot></a>
    `;
  }

  /**
   * A selector that will return the nav bar.
   */
  static get selectorTopNav() {
    return `${ddsPrefix}-top-nav`;
  }

  static get stableSelector() {
    return `${ddsPrefix}--masthead__platform-name`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSTopNavName;
