/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { property, query, customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import BXHeaderMenu from 'carbon-web-components/es/components/ui-shell/header-menu.js';
import styles from './masthead.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Masthead top nav submenu.
 *
 * @element dds-top-nav-menu
 */
@customElement(`${ddsPrefix}-top-nav-menu`)
class DDSTopNavMenu extends BXHeaderMenu {
  /**
   * The trigger button.
   */
  @query('[part="trigger"]')
  private _triggerNode?: HTMLAnchorElement;

  /**
   * `true` if this submenu should be in its active state.
   */
  @property({ type: Boolean, reflect: true })
  active = false;

  updated(changedProperties) {
    super.updated(changedProperties);
    if (changedProperties.has('active')) {
      const { active, _triggerNode: triggerNode } = this;
      if (triggerNode) {
        triggerNode.setAttribute('aria-selected', String(Boolean(active)));
      }
    }
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSTopNavMenu;
