/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import { BXHeaderNavItemBase } from '@carbon/web-components/es/components/ui-shell/header-nav-item';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './masthead.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Masthead top nav submenu item.
 *
 * @element dds-top-nav-menu-item
 */
@customElement(`${ddsPrefix}-top-nav-menu-item`)
class DDSTopNavMenuItem extends BXHeaderNavItemBase {
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader

  firstUpdated() {
    this.shadowRoot
      ?.querySelectorAll('[role="menuitem"]')
      .forEach((menuItem) => menuItem.removeAttribute('role'));
  }
}

export default DDSTopNavMenuItem;
