/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { property } from 'lit-element';
import BXModalHeader from '../../internal/vendor/@carbon/web-components/components/modal/modal-header.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './expressive-modal.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element.js';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Expressive modal header.
 *
 * @element dds-expressive-modal-header
 */
@customElement(`${ddsPrefix}-expressive-modal-header`)
class DDSExpressiveModalHeader extends StableSelectorMixin(BXModalHeader) {
  @property({ reflect: true })
  slot = 'header';

  static get stableSelector() {
    return `${ddsPrefix}--expressive-modal-header`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSExpressiveModalHeader;
