/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit/decorators.js';
import BXModalBody from '@carbon/web-components/es/components/modal/modal-body.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './expressive-modal.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Expressive modal body.
 *
 * @element dds-expressive-modal-body
 */
@customElement(`${ddsPrefix}-expressive-modal-body`)
class DDSExpressiveModalBody extends StableSelectorMixin(BXModalBody) {
  static get stableSelector() {
    return `${ddsPrefix}--expressive-modal-body`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSExpressiveModalBody;
