/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { property } from 'lit-element';
import BXModalCloseButton from '../../internal/vendor/@carbon/web-components/components/modal/modal-close-button.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { EXPRESSIVE_MODAL_SIZE } from './defs';
import styles from './expressive-modal.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import { carbonElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element.js';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Expressive modal close button.
 *
 * @element dds-expressive-modal-close-button
 */
@carbonElement(`${ddsPrefix}-expressive-modal-close-button`)
class DDSExpressiveModalCloseButton extends StableSelectorMixin(
  BXModalCloseButton
) {
  /**
   * The size variant.
   */
  @property({ reflect: true, attribute: 'size' })
  size = EXPRESSIVE_MODAL_SIZE.REGULAR;

  static get stableSelector() {
    return `${ddsPrefix}--expressive-modal-close-button`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSExpressiveModalCloseButton;
