/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, css, customElement, TemplateResult } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSContentGroup from '../content-group/content-group';
import styles from './content-group-cards.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content group cards.
 *
 * @element dds-content-group-cards
 * @slot copy - The copy
 * @slot content - The card items content
 */
@customElement(`${ddsPrefix}-content-group-cards`)
class DDSContentGroupCards extends StableSelectorMixin(DDSContentGroup) {
  /**
   * @returns The copy content.
   */
  // eslint-disable-next-line class-methods-use-this
  protected _renderCopy(): TemplateResult | string | void {
    return html`
      <div class="${prefix}--content-group__copy">
        <slot></slot>
      </div>
    `;
  }

  /**
   * @returns The main content.
   */
  // eslint-disable-next-line class-methods-use-this
  protected _renderContent(): TemplateResult | string | void {
    return html`
      <div class="${prefix}--content-group__children ${prefix}--content-group__col">
        <div class="${prefix}--content-group-cards-group ${prefix}--grid--condensed">
          <div class="${prefix}--content-group-cards__row">
            <slot name="content"></slot>
          </div>
        </div>
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-group-cards`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSContentGroupCards;
