/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { css, property, customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import styles from './logo-grid.scss';
import DDSCardLink from '../card-link/card-link';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Logo-grid-link.
 *
 * @element dds-logo-grid-link
 */
@customElement(`${ddsPrefix}-logo-grid-link`)
class DDSLogoGridLink extends StableSelectorMixin(DDSCardLink) {
  /**
   * The shadow slot this link should be in.
   */
  @property({ reflect: true })
  slot = 'footer';

  static get stableSelector() {
    return `${ddsPrefix}--logo-grid-link`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSLogoGridLink;
