/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { property, customElement, LitElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import { HR_TYPE, HR_SIZE, HR_CONTRAST, HR_WEIGHT } from './defs';
import styles from './horizontal-rule.scss';

export { HR_TYPE, HR_SIZE, HR_CONTRAST, HR_WEIGHT };

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Horizontal Rule
 *
 * @element dds-hr
 */
@customElement(`${ddsPrefix}-hr`)
class DDSHorizontalRule extends StableSelectorMixin(LitElement) {
  /**
   * Style of the HR (solid (default) | dashed)
   */
  @property({ attribute: 'type', reflect: true })
  type = HR_TYPE.SOLID;

  /**
   * Length of the HR
   * (fluid (default) | small | medium | large)
   */
  @property({ attribute: 'size', reflect: true })
  size = HR_SIZE.FLUID;

  /**
   * Contrast of the HR
   * (medium-contrast (default) | low-contrast | high-contrast)
   */
  @property({ attribute: 'contrast', reflect: true })
  contrast = HR_CONTRAST.MEDIUM_CONTRAST;

  /**
   * Weight of the HR
   * (thin (default) | thick)
   */
  @property({ attribute: 'weight', reflect: true })
  weight = HR_WEIGHT.THIN;

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'separator');
    }
    super.connectedCallback();
  }

  static get stableSelector() {
    return `${ddsPrefix}--hr`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSHorizontalRule;
