/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { customElement, css } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import DDSLinkWithIcon from '../link-with-icon/link-with-icon';
import styles from './callout-quote.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Callout link with item
 *
 * @element dds-callout-link-with-icon
 */
@customElement(`${ddsPrefix}-callout-link-with-icon`)
class DDSCalloutLinkWithIcon extends DDSLinkWithIcon {
  static get stableSelector() {
    return `${ddsPrefix}--callout-link-with-icon`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSCalloutLinkWithIcon;
