/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css } from 'lit';
import settings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';
import C4DLinkWithIcon from '../link-with-icon/link-with-icon';
import styles from './callout-quote.scss';

const { stablePrefix: ddsPrefix } = settings;

/**
 * Callout link with item
 *
 * @element c4d-callout-link-with-icon
 */
@customElement(`${ddsPrefix}-callout-link-with-icon`)
class C4DCalloutLinkWithIcon extends C4DLinkWithIcon {
  static get stableSelector() {
    return `${ddsPrefix}--callout-link-with-icon`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default C4DCalloutLinkWithIcon;
