/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, customElement, LitElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import sameHeight from '@carbon/ibmdotcom-utilities/es/utilities/sameHeight/sameHeight';
import styles from './card-group.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Card Group.
 * @element dds-card-group
 */
@customElement(`${ddsPrefix}-card-group`)
class DDSCardGroup extends LitElement {

  private childItems;

  render() {
    return html`
      <slot @slotchange="${this._handleSlotChange}"></slot>
    `;
  }

  connectedCallback() {
    super.connectedCallback();
    window.addEventListener('resize', this._handleResize);
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    window.removeEventListener('resize', this._handleResize);
  }

  /**
   * Method called on resize, triggers the sameHeight utility
   *
   * @private
   */
  private _handleResize() {
    if (this.childItems) window.requestAnimationFrame(() => sameHeight(this.childItems, 'md'));
  }

  /**
   * Handler for @slotChange, toggles the split layout class and set the children link-list-item to the same height
   *
   * @private
   */
  private _handleSlotChange(event: Event) {
    this.childItems = (event.target as HTMLSlotElement)
      .assignedNodes({ flatten: true })
      .filter(elem => (elem as HTMLElement).localName === (this.constructor as typeof DDSCardGroup).cardGroupItemSelector);

    sameHeight(this.childItems, 'lg');
  }

  /**
   * A selector that will return card group items.
   */
  static get cardGroupItemSelector() {
    return `${ddsPrefix}-card-group-item`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSCardGroup;
