/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './feature-card-block-medium.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The block heading content of feature card block medium.
 *
 * @element dds-feature-card-block-medium-block-heading
 */
@customElement(`${ddsPrefix}-feature-card-block-medium-block-heading`)
class DDSFeatureCardBlockMediumBlockHeading extends LitElement {
  /**
   * The shadow slot this block heading should be in.
   */
  @property({ reflect: true })
  slot = 'block-heading';

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'heading');
    }
    if (!this.hasAttribute('aria-level')) {
      this.setAttribute('aria-level', '3');
    }
    super.connectedCallback();
  }

  render() {
    return html` <slot></slot> `;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static styles = styles;
}

export default DDSFeatureCardBlockMediumBlockHeading;
