/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, css } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import styles from './leadspace-with-search.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSContentBlockParagraph from '../content-block/content-block-paragraph';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The paragraph content in content block.
 *
 * @element dds-leadspace-search-block-copy
 */
@customElement(`${ddsPrefix}-leadspace-search-block-copy`)
class DDSLeadspaceBlockCopy extends StableSelectorMixin(DDSContentBlockParagraph) {
  static get stableSelector() {
    return `${ddsPrefix}--leadspace-search-block-copy`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSLeadspaceBlockCopy;
