/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, property } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSLeadspaceBlockContent from '../leadspace-block/leadspace-block-content';
import styles from './leadspace-with-search.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content in Leadspace with search.
 *
 * @element dds-leadspace-block-content
 */
@customElement(`${ddsPrefix}-leadspace-with-search-content`)
class DDSLeadspaceWithSearchContent extends StableSelectorMixin(
  DDSLeadspaceBlockContent
) {
  /**
   * The shadow slot the content should be in.
   */
  @property({ reflect: true })
  slot = 'content';

  static get stableSelector() {
    return `${ddsPrefix}--leadspace-with-search__content`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSLeadspaceWithSearchContent;
