/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSLeadspaceBlockHeading from '../leadspace-block/leadspace-block-heading';
import styles from './leadspace-with-search.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Heading in Leadspace with search.
 *
 * @element dds-leadspace-with-search-heading
 */
@customElement(`${ddsPrefix}-leadspace-with-search-heading`)
class DDSLeadspaceWithSearchHeading extends StableSelectorMixin(
  DDSLeadspaceBlockHeading
) {
  static get stableSelector() {
    return `${ddsPrefix}--leadspace-with-search__heading`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSLeadspaceWithSearchHeading;
