/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import settings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';
import C4DLeadspaceBlockHeading from '../leadspace-block/leadspace-block-heading';
import styles from './leadspace-with-search.scss';

const { stablePrefix: ddsPrefix } = settings;

/**
 * Heading in Leadspace with search.
 *
 * @element c4d-leadspace-with-search-heading
 */
@customElement(`${ddsPrefix}-leadspace-with-search-heading`)
class C4DLeadspaceWithSearchHeading extends StableSelectorMixin(
  C4DLeadspaceBlockHeading
) {
  static get stableSelector() {
    return `${ddsPrefix}--leadspace-with-search__heading`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default C4DLeadspaceWithSearchHeading;
