/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css, customElement, html } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import DDSContentGroup from '../content-group/content-group';
import '../horizontal-rule/horizontal-rule';
import styles from './content-block-horizontal.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Horizontal version of content group.
 *
 * @element dds-content-block-horizontal
 */
@customElement(`${ddsPrefix}-content-block-horizontal`)
class DDSContentBlockHorizontal extends DDSContentGroup {
  render() {
    return html`
      ${super.render()}
      <dds-hr></dds-hr>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-block-horizontal`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSContentBlockHorizontal;
