/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, html, LitElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
// import settings from 'carbon-components/es/globals/js/settings';
// import Close from 'carbon-web-components/es/icons/close/16';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

import styles from './filter-panel.scss';

// const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

@customElement(`${ddsPrefix}-checkbox`)
class DDSCheckbox extends StableSelectorMixin(LitElement) {
  render() {
    return html`
      <fieldset class="bx--fieldset">
        <!-- input + label -->
        <div class="bx--form-item bx--checkbox-wrapper">
          <input id="bx--checkbox-new" class="bx--checkbox" type="checkbox" value="new" name="checkbox" checked />
          <label for="bx--checkbox-new" class="bx--checkbox-label">Checkbox</label>
        </div>
        <!-- input + label indeterminate -->
        <div class="bx--form-item bx--checkbox-wrapper">
          <input id="bx--checkbox-ind" class="bx--checkbox" type="checkbox" value="new" name="checkbox" aria-checked="mixed" />
          <label for="bx--checkbox-ind" class="bx--checkbox-label">Indeterminate check</label>
        </div>
      </fieldset>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSCheckbox;
