/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import BXModalHeading from '../../internal/vendor/@carbon/web-components/components/modal/modal-heading.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './filter-panel.scss';
import { carbonElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element.js';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Extends the BXModalHeading
 *
 * @element dds-filter-modal-heading
 */
@carbonElement(`${ddsPrefix}-filter-modal-heading`)
class DDSFilterModalHeading extends StableSelectorMixin(BXModalHeading) {
  static get stableSelector() {
    return `${ddsPrefix}-filter-modal-heading`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSFilterModalHeading;
