/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {
  customElement,
  html,
  // property,
  LitElement,
  internalProperty,
  property,
} from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import settings from 'carbon-components/es/globals/js/settings';
import { classMap } from 'lit-html/directives/class-map';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import './input_select';

import styles from './filter-panel.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

@customElement(`${ddsPrefix}-filter-group`)
class DDSFilterGroup extends StableSelectorMixin(LitElement) {
  @internalProperty()
  protected _childItems: Element[] = [];

  @internalProperty()
  private selectorItem: string = '';

  private _handleSlotChange(event: Event) {
    this._childItems = (event.target as HTMLSlotElement)
      .assignedNodes({ flatten: true })
      .filter(node => node.nodeType === Node.ELEMENT_NODE && (node as Element)?.matches(this.selectorItem)) as Element[];
  }

  @property()
  title: string = '';

  @internalProperty()
  private isOpen: boolean = true;

  protected toggleAccordion() {
    this.isOpen = !this.isOpen;
  }

  render() {
    const { title, isOpen } = this;
    const classes = classMap({
      'bx--accordion__item': true,
      'bx--accordion__item--active': isOpen,
    });
    return html`
      <ul class="${prefix}--accordion">
        <li data-accordion-item class="${classes}">
          <button
            class="bx--accordion__heading"
            aria-expanded="false"
            aria-controls="pane1"
            @click=${() => this.toggleAccordion()}
          >
            <svg
              focusable="false"
              preserveAspectRatio="xMidYMid meet"
              style="will-change: transform;"
              xmlns="http://www.w3.org/2000/svg"
              class="bx--accordion__arrow"
              width="16"
              height="16"
              viewBox="0 0 16 16"
              aria-hidden="true"
            >
              <path d="M11 8L6 13 5.3 12.3 9.6 8 5.3 3.7 6 3z"></path>
            </svg>
            <div class="bx--accordion__title">${title}</div>
          </button>
          <div class="bx--accordion__content">
            <slot @slotchange="${this._handleSlotChange}"></slot>
          </div>
        </li>
      </ul>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSFilterGroup;
