/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, css } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSContentGroup from '../content-group/content-group';
import styles from './content-group-pictograms.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content group with pictograms
 *
 * @element dds-content-group-pictogram
 */

@customElement(`${ddsPrefix}-content-group-pictograms`)
class DDSContentGroupPictograms extends StableSelectorMixin(DDSContentGroup) {
  static get stableSelector() {
    return `${ddsPrefix}--content-group-pictograms`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSContentGroupPictograms;
