/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css } from 'lit-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { carbonElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';
import DDSContentGroup from '../content-group/content-group';
import styles from './content-group-pictograms.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content group with pictograms
 *
 * @element dds-content-group-pictogram
 */

@carbonElement(`${ddsPrefix}-content-group-pictograms`)
class DDSContentGroupPictograms extends DDSContentGroup {
  static get stableSelector() {
    return `${ddsPrefix}--content-group-pictograms`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSContentGroupPictograms;
