/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import DDSCardFooter from '../cta/card-cta-footer';

import styles from './card-in-card.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Card in Card footer.
 *
 * @element dds-card-in-card-footer
 */
@customElement(`${ddsPrefix}-card-in-card-footer`)
class DDSCardInCardFooter extends DDSCardFooter {
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSCardInCardFooter;
