/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { property, customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import BXModalFooter from 'carbon-web-components/es/components/modal/modal-footer.js';
import styles from './modal.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Expressive modal footer.
 *
 * @element dds-modal-footer
 */
@customElement(`${ddsPrefix}-modal-footer`)
class DDSModalFooter extends BXModalFooter {
  @property({ reflect: true })
  slot = 'footer';

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSModalFooter;
