/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import BXModalBody from 'carbon-web-components/es/components/modal/modal-body.js';
import styles from './modal.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Expressive modal body.
 *
 * @element dds-modal-body
 */
@customElement(`${ddsPrefix}-modal-body`)
class DDSModalBody extends BXModalBody {
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSModalBody;
