/**
 * @license
 *
 * Copyright IBM Corp. 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement } from 'lit-element';
import { classMap } from 'lit-html/directives/class-map';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import styles from './background-media.scss';
import { GRADIENT_DIRECTION, MOBILE_POSITION } from './defs';
import DDSImage from '../image/image';
import DDSVideoPlayer from '../video-player/video-player';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Background media.
 *
 * @element dds-background-media
 */

@customElement(`${ddsPrefix}-background-media`)
class DDSBackgroundMedia extends DDSImage {
  /**
   * Returns a class-name based on the Gradient Direction type
   */
  protected _getGradientClass() {
    return classMap({
      [`${prefix}--background-media--gradient`]: true,
      [`${prefix}--background-media--gradient--${this.gradientDirection}`]: this.gradientDirection,
    });
  }

  /**
   * Returns a class-name based on the Mobile Position type
   */
  protected _getMobilePositionClass() {
    return classMap({
      [`${prefix}--background-media--mobile-position`]: true,
      [`${prefix}--background-media--mobile-position--${this.mobilePosition}`]: this.mobilePosition,
    });
  }

  /**
   * Gradient Direction (left-to-right (default) | top-to-bottom)
   */
  @property({ attribute: 'gradient-direction', reflect: true })
  gradientDirection = GRADIENT_DIRECTION.LEFT_TO_RIGHT;

  /**
   * Mobile Position (bottom (default) | top)
   */
  @property({ attribute: 'mobile-position', reflect: true })
  mobilePosition = MOBILE_POSITION.BOTTOM;

  /**
   * Set to true in _handleBackgroundMedia if all children are `dds-image-item`
   */
  @property()
  containsOnlyImages = false;

  /**
   * Set to true in _handleBackgroundMedia if any children are `dds-video-player-container`
   */
  @property()
  videoId: String | null = null;

  @property()
  videoPlayer: DDSVideoPlayer | null = null;

  /**
   * Conditionally runs super.render() if all children are `dds-image-item`
   */
  private _handleBackgroundMedia(event: Event) {
    const assignedElements = (event.target as HTMLSlotElement)?.assignedElements();
    const assignedImages = assignedElements.filter(el => el.tagName === `${ddsPrefix}-image-item`.toUpperCase());
    const assignedVideos = assignedElements.filter(el => el.tagName === `${ddsPrefix}-video-player-container`.toUpperCase());

    if (assignedElements.length === assignedImages.length && assignedImages.length > 0) {
      this.containsOnlyImages = true;
    }

    if (assignedVideos.length) {
      const [video] = assignedVideos;
      this.videoId = video.getAttribute('video-id');
      this.videoPlayer = video.querySelector(`${ddsPrefix}-video-player`);
    }
  }

  toggleVideoState() {
    this.videoPlayer?.userInitiatedTogglePlaybackState();

    // TODO: Implement aria-pressed, visual changes for button state
  }

  /**
   * Append the dds-background-media to the parent element where this component is being used.
   */
  updated() {
    if (this.mobilePosition === MOBILE_POSITION.TOP) {
      this.parentElement?.shadowRoot?.prepend(this);
    }
  }

  renderVideoControls() {
    return html`
      <button @click=${this.toggleVideoState} class="${prefix}--video-player__controls">Play/Pause</button>
    `;
  }

  render() {
    return html`
      <div class="${this._getMobilePositionClass()}">
        <div class="${this._getGradientClass()}"></div>
        ${this.containsOnlyImages ? super.render() : ''}
        <slot @slotchange="${this._handleBackgroundMedia}"></slot>
        ${this.videoId ? this.renderVideoControls() : ''}
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--background-media`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSBackgroundMedia;
