/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import styles from '@carbon/ibmdotcom-styles/scss/components/dotcom-shell/_dotcom-shell.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Dotcom shell.
 *
 * @element dds-dotcom-shell
 */
@customElement(`${ddsPrefix}-dotcom-shell`)
class DDSDotcomShell extends StableSelectorMixin(LitElement) {
  // eslint-disable-next-line class-methods-use-this
  render() {
    return html`
      <div class="${prefix}--dotcom-shell__content">
        <slot></slot>
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--dotcom-shell`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSDotcomShell;
