/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, html, property, LitElement, TemplateResult } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import ifNonNull from 'carbon-web-components/es/globals/directives/if-non-null.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

import styles from './cta-section.scss';

// eslint-disable-next-line
const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The CTA Section pattern
 *
 * @element dds-cta-section
 */
@customElement(`${ddsPrefix}-cta-section`)
class DDSCTASection extends StableSelectorMixin(LitElement) {
  /**
   * Applies section attribute
   */
  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'section');
    }
    super.connectedCallback();
  }

  protected _renderBody(): TemplateResult | string | void {
    // const { _hasFooter: hasFooter } = this;
    return html`
      ${this._renderCopy()} ${this._renderContent()}
    `;
  }

  // eslint-disable-next-line class-methods-use-this
  protected _renderContent(): TemplateResult | string | void {
    return html`
      <slot></slot>
    `;
  }

  protected _renderCopy(): TemplateResult | string | void {
    const { copy } = this;
    return html`
      ${!copy
        ? undefined
        : html`
            <dds-markdown class="${ddsPrefix}--content-block__copy" nobold .content="${ifNonNull(copy)}"></dds-markdown>
          `}
    `;
  }

  /**
   * The Content Section heading.
   */
  @property()
  heading = '';

  @property()
  copy = '';

  render() {
    return html`
      <slot name="heading"></slot>
      ${this._renderBody()}
    `;
  }

  /**
   * 
   * <section
      data-autoid={`${stablePrefix}--cta-section`}
      className={classNames(`${prefix}--cta-section`, {
        [`${prefix}--cta-section__has-items`]: items,
        [`${prefix}--cta-section--${theme}`]: theme,
      })}
      ref={containerRef}>
      <ContentBlock heading={heading} copy={copy} />
      <CTA customClassName={`${prefix}--cta-section__cta`} {...cta} />
      {items && (
        <div className={`${prefix}--helper-wrapper`}>
          <div className={`${prefix}--content-item-wrapper`}>
            {items.map((item, index) => (
              <ContentItem
                key={index}
                heading={item.heading}
                copy={item.copy}
                cta={item.cta}
              />
            ))}
          </div>
        </div>
      )}
    </section>
   */

  static get stableSelector() {
    return `${ddsPrefix}--cta-section`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSCTASection;
