name: ci-check-integration-ui
on:
  push:
    branches:
      - 'test/*'
  pull_request:
    branches:
      - 'test/*'

jobs:
  integration-ui:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: ['14.x']
        browser: [chromium, firefox]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Run web-component-analyzer
        run: yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-web-components wca
      - name: Install xvfb
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install xvfb
      - name: Run checks with xvfb (React)
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run --auto-servernum yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-react test:integration:ui
        env:
          DDS_UI_INTEGRATION_TEST_BROWSER: ${{ matrix.browser }}
          DDS_UI_INTEGRATION_TEST_TIMEOUT: 60000
          LAUNCH_TIMEOUT: 600000
      - name: Run checks with xvfb (Web Components)
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run --auto-servernum yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-web-components test:integration:ui
        env:
          DDS_UI_INTEGRATION_TEST_BROWSER: ${{ matrix.browser }}
          DDS_UI_INTEGRATION_TEST_TIMEOUT: 60000
          LAUNCH_TIMEOUT: 600000
      - name: Run checks without xvfb (React)
        if: matrix.os != 'ubuntu-latest'
        run: yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-react test:integration:ui
        env:
          DDS_UI_INTEGRATION_TEST_BROWSER: ${{ matrix.browser }}
          DDS_UI_INTEGRATION_TEST_TIMEOUT: 60000
          LAUNCH_TIMEOUT: 600000
      - name: Run checks without xvfb (Web Components)
        if: matrix.os != 'ubuntu-latest'
        run: yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-web-components test:integration:ui
        env:
          DDS_UI_INTEGRATION_TEST_BROWSER: ${{ matrix.browser }}
          DDS_UI_INTEGRATION_TEST_TIMEOUT: 60000
          LAUNCH_TIMEOUT: 600000
