name : Cut Release branch
on:
  workflow_dispatch:
    inputs:
      version-number:
        required: true
        description: 'version number (ie: 2.3.0)'
        type: string
        default: '2.x.x'
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GH_TOKEN: ${{ secrets.MERGE_ACTION }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
      - name: Config github user
        run: |
          git config --global user.email "digdes@us.ibm.com"
          git config --global user.name "ibmdotcom-bot"
      - name: Create the release branch
        run: git checkout -b release/v${{ github.event.inputs.version-number }}
      - name: Push the Relese branch
        run: git push --set-upstream origin release/v${{ github.event.inputs.version-number }}
