name: deploy-preview-cwc (Deploy Preview - Carbon Web Components)

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build package
        run: yarn lerna run --scope @carbon/web-components build
      - name: Build @carbon/web-components Storybook
        run: yarn build-storybook
        working-directory: packages/carbon-web-components
