name: publish-canary-cdn (Publish Canary release to CDN)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn build
      - name: Create CDN artifacts
        run: yarn build:sass:cdn && yarn build:components
        working-directory: packages/web-components
      - name: Publish to COS (Carbon for IBM.com Web Components)
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.COS_BUCKET_COMMON }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COS_ENDPOINT }}
          SOURCE_DIR: 'packages/web-components/dist'
          DEST_DIR: 'common/carbon-for-ibm-dotcom/tag/v1/canary'
#      - name: Publish to COS (Carbon Web Components)
#        uses: jakejarvis/s3-sync-action@master
#        with:
#          args: --acl public-read --follow-symlinks
#        env:
#          AWS_S3_BUCKET: ${{ secrets.COS_BUCKET_COMMON }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.COS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.COS_SECRET_ACCESS_KEY }}
#          AWS_REGION: ${{ secrets.COS_REGION }}
#          AWS_S3_ENDPOINT: https://${{ secrets.COS_ENDPOINT }}
#          SOURCE_DIR: 'packages/carbon-web-components/dist'
#          DEST_DIR: 'common/carbon/web-components/tag/v2/canary'
      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
        if: failure()
