name: Release Notifications

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  post-comments:
    name: Post notification comments on PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Add release information on pull requests
        run: node tasks/release-notifications.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}