name: test-integration-react

on: [push, pull_request]

jobs:
  test-integration-react:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Build
        run: yarn build
      - name: Run build integration test
        run: xvfb-run --auto-servernum yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-react test:integration:build
      - name: Run bundle integration test
        run: yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-react test:integration:bundle
