/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit-html/directives/class-map';
import { internalProperty, customElement, html, LitElement, property } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import { LINK_LIST_TYPE } from './defs';
import styles from './link-list.scss';

export { LINK_LIST_TYPE };

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Link list.
 *
 * @element dds-link-list
 * @slot heading - The heading content.
 */
@customElement(`${ddsPrefix}-link-list`)
class DDSLinkList extends StableSelectorMixin(LitElement) {
  /**
   * `true` to use "split mode" layout for `type="end"`.
   * Should happen if there are more than three child items slotted in.
   */
  @internalProperty()
  private _useSplitLayoutForEndType = false;

  /**
   * Handler for @slotChange, toggles the split layout class and set the children link-list-item to the same height
   *
   * @private
   */
  private _handleSlotChange(event: Event) {
    const { selectorItem } = this.constructor as typeof DDSLinkList;
    const childItems = (event.target as HTMLSlotElement)
      .assignedNodes({ flatten: true })
      .filter(node => node.nodeType === Node.ELEMENT_NODE && (node as Element)?.matches(selectorItem)) as Element[];
    this._useSplitLayoutForEndType = childItems.length > 3;
  }

  /**
   * The link list type.
   */
  @property({ reflect: true })
  type = LINK_LIST_TYPE.DEFAULT;

  render() {
    const { type, _useSplitLayoutForEndType: useSplitLayoutForEndType } = this;
    const headingClasses = classMap({
      [`${ddsPrefix}-ce--link-list__heading__wrapper`]: true,
      [`${ddsPrefix}-ce--link-list__heading--split`]: type === LINK_LIST_TYPE.END && useSplitLayoutForEndType,
    });
    const listTypeClasses =
      {
        [LINK_LIST_TYPE.HORIZONTAL]: `${prefix}--link-list__list--horizontal`,
        [LINK_LIST_TYPE.VERTICAL]: `${prefix}--link-list__list--vertical`,
        [LINK_LIST_TYPE.END]: `${ddsPrefix}-ce--link-list__list--end`,
      }[type] ?? `${prefix}--link-list__list--card`;
    const listClasses = classMap({
      [`${prefix}--link-list__list`]: true,
      [listTypeClasses]: true,
      [`${ddsPrefix}-ce--link-list__list--split`]: type === LINK_LIST_TYPE.END && useSplitLayoutForEndType,
    });
    return html`
      <div class="${headingClasses}"><slot name="heading"></slot></div>
      <ul name="list" class="${listClasses}">
        <slot @slotchange="${this._handleSlotChange}"></slot>
      </ul>
    `;
  }

  /**
   * A selector selecting the child items.
   */
  static get selectorItem() {
    return `${ddsPrefix}-link-list-item`;
  }

  static get stableSelector() {
    return `${ddsPrefix}--link-list`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLinkList;
