/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { html, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import styles from './link-list.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Link list item.
 *
 * @element dds-link-list-item
 */
@customElement(`${ddsPrefix}-link-list-item`)
class DDSLinkListItem extends LitElement {
  // eslint-disable-next-line class-methods-use-this
  protected render() {
    return html`
      <li class="${prefix}--link-list__list__CTA">
        <slot />
      </li>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--link-list-item`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLinkListItem;
