/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { html, customElement, property, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import styles from './link-list.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Link list.
 *
 * @element dds-link-list
 */
@customElement(`${ddsPrefix}-link-list`)
class DDSLinkList extends LitElement {
  @property({ type: String })
  type = 'default';

  // eslint-disable-next-line class-methods-use-this
  protected render() {
    return html`
      <div class="${prefix}--link-list" data-autoid="${(this.constructor as typeof DDSLinkList).stableSelector}">
        <h4 class="${prefix}--link-list__heading"><slot name="heading" /></h4>
        <ul name="list" class="${prefix}--link-list__list ${this.ulClasses()}">
          <slot />
        </ul>
      </div>
    `;
  }

  protected ulClasses() {
    switch (this.type) {
      case 'horizontal':
        return `${prefix}--link-list__list--horizontal`;
      case 'vertical':
        return `${prefix}--link-list__list--vertical`;
      case 'end':
        return `${prefix}--link-list__list--end`;
      default:
        return `${prefix}--link-list__list--card`;
    }
  }

  static get stableSelector() {
    return `${ddsPrefix}--link-list`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLinkList;
